### ISSUE TITLE
TypeError when calling liffy

### ISSUE THREAD

**Issue by craig** [mzfr/liffy#22]
```
(liffy) [user@host ~/liffy ]$ python liffy.py "http://xxxxx:49768/?file="  -a -l /var/apache2/access.log 
 _      _  __  __              ___    ___  
| |    (_)/ _|/ _|            |__ \  / _ \ 
| |     _| |_| |_ _   _  __   __ ) || | | |
| |    | |  _|  _| | | | \ \ / // / | | | |
| |____| | | | | | |_| |  \ V // /_ | |_| |
|______|_|_| |_|  \__, |   \_/|____(_)___/ 
                   __/ |                   
                  |___/                    



[~] Checking Target: xxxxxxx:49768
[~] Testing for Apache access.log poisoning
Traceback (most recent call last):
  File "/home/user/liffy/liffy.py", line 131, in <module>
    main()
  File "/home/user/liffy/liffy.py", line 102, in main
    a = accesslog(url, l, nostager, relative, cookies)
TypeError: 'module' object is not callable

```

$ python --version
Python 3.9.2

**Comment by mzfr** [comment]
Fixed by #23
